import pandas as pd
import numpy as np
import ast

class SkincareMatchingEngine:
    def __init__(self, database_path):
        # Load the database
        self.df = pd.read_csv(database_path)
        
        # Ensure array columns are actually Python lists, not strings
        for col in ['efficacy_vector', 'clean_ingredient_array', 'conflict_tags']:
            if isinstance(self.df[col].iloc[0], str):
                self.df[col] = self.df[col].apply(ast.literal_eval)

    def is_safe_combination(self, anchor_product, candidate_product):
        """Performs the two-way set intersection check using normalized active keys."""
        
        # Grab the normalized strings we generated in score_engine.py
        anchor_actives = set(anchor_product.get('recognized_actives', []))
        anchor_enemies = set(anchor_product.get('conflict_tags', []))
        
        candidate_actives = set(candidate_product.get('recognized_actives', []))
        candidate_enemies = set(candidate_product.get('conflict_tags', []))
        
        # 1. Does the candidate contain an ACTIVE the anchor HATES?
        if len(anchor_enemies.intersection(candidate_actives)) > 0:
            return False
            
        # 2. Does the anchor contain an ACTIVE the candidate HATES?
        if len(candidate_enemies.intersection(anchor_actives)) > 0:
            return False
            
        return True # It is safe!

    def build_routine(self, user_vector, price_tier):
        user_np = np.array(user_vector)
        
        # --- NEW LOGIC: Calculate the Theoretical Maximum ---
        # A "Perfect" product has an 8.0 in every single category
        perfect_product_vector = np.array([8.0, 8.0, 8.0, 8.0, 8.0, 8.0])
        theoretical_max_score = np.dot(user_np, perfect_product_vector)
        
        # Safety check: If user entered all 0s, default max to 1 to prevent division by zero
        if theoretical_max_score == 0:
            theoretical_max_score = 1.0 
        # ----------------------------------------------------

        tier_df = self.df[self.df['price_tier'] == price_tier].copy()
        
        if tier_df.empty:
            return "Error: No products found in this price tier."

        # Calculate Raw Dot Product
        tier_df['raw_score'] = tier_df['efficacy_vector'].apply(lambda v: np.dot(user_np, np.array(v)))
        
        # --- NEW LOGIC: Convert to Percentage ---
        tier_df['match_percent'] = (tier_df['raw_score'] / theoretical_max_score) * 100
        # Cap at 100% (just in case pooling math ever exceeds 8.0) and round it
        tier_df['match_percent'] = tier_df['match_percent'].clip(upper=100).round(1)
        # ----------------------------------------------------

        # (The rest of your selection logic remains the same, just change the sort column)
        
        treatments = tier_df[tier_df['routine_step'] == 'Treatment']
        if treatments.empty:
             return "Error: No treatments found."
             
        # Sort by the new percentage!
        anchor_treatment = treatments.sort_values(by='match_percent', ascending=False).iloc[0]
        
        # 3. SELECT CLEANSER (With Conflict Check)
        cleansers = tier_df[tier_df['routine_step'] == 'Cleanser'].sort_values(by='match_percent', ascending=False)
        best_cleanser = None
        
        for _, cleanser in cleansers.iterrows():
            if self.is_safe_combination(anchor_treatment, cleanser):
                best_cleanser = cleanser
                break # Stop at the first (highest scoring) safe cleanser
                
        # 4. SELECT MOISTURIZER (With Conflict Check)
        moisturizers = tier_df[tier_df['routine_step'] == 'Moisturizer'].sort_values(by='match_percent', ascending=False)
        best_moisturizer = None
        
        for _, moisturizer in moisturizers.iterrows():
            if self.is_safe_combination(anchor_treatment, moisturizer):
                # Optionally: You could also check if it conflicts with the Cleanser here!
                if self.is_safe_combination(best_cleanser, moisturizer):
                    best_moisturizer = moisturizer
                    break
        
        # 5. RETURN THE FINAL ROUTINE
        return {
            "Step 1 (Cleanser)": best_cleanser.to_dict() if best_cleanser is not None else "No safe match found",
            "Step 2 (Treatment)": anchor_treatment.to_dict(),
            "Step 3 (Moisturizer)": best_moisturizer.to_dict() if best_moisturizer is not None else "No safe match found"
        }
if __name__ == "__main__":
    print("🚀 Initializing Skincare Matching Engine...")
    
    # 1. Instantiate the Engine
    # Make sure this path points to the file generated by your ingestion script
    DATABASE_PATH = 'dataset/final_sephora_database.csv' 
    
    try:
        engine = SkincareMatchingEngine(DATABASE_PATH)
        print(f"✅ Database loaded successfully. {len(engine.df)} products ready.")
    except FileNotFoundError:
        print(f"❌ Error: Could not find {DATABASE_PATH}. Did you run the ingestion script?")
        exit()

    # 2. Simulate Frontend/CV Output
    # The order MUST match your CONDITIONS_ORDER: 
    # [acne, blackheads, dark_spots, pores, wrinkles, eyebags]
    
    # Example User: Severe acne, moderate blackheads, large pores. Doesn't care about wrinkles.
    MOCK_USER_VECTOR = [1.0, 0.6, 0.0, 0.8, 0.0, 0.0] 
    MOCK_USER_BUDGET = "Budget"

    print("\n" + "="*50)
    print("🔎 RUNNING MATCHING ALGORITHM")
    print("="*50)
    print(f"User Vector: {MOCK_USER_VECTOR}")
    print(f"Price Tier:  {MOCK_USER_BUDGET}\n")

    # 3. Execute the Algorithm
    routine = engine.build_routine(MOCK_USER_VECTOR, MOCK_USER_BUDGET)

    # 4. Display the Results
    if isinstance(routine, str):
        # Catches the error messages returned by the engine (e.g., "No products found")
        print(routine)
    else:
        for step, product in routine.items():
            print(f"\n🟩 {step.upper()}")
            if isinstance(product, dict):
                print(f"   Name:       {product.get('product_name', 'Unknown')}")
                print(f"   Brand:      {product.get('brand_name', 'Unknown')}")
                print(f"   Price:      ${product.get('price_usd', 0.00)}")
                print(f"   Rating:     {product.get('rating', 0.00):.2f}/5.0")
                print(f"   Actives:    {product.get('clean_ingredient_array', [])[:5]}...") # Just show first 5
                print(f"   Conflicts:  {product.get('conflict_tags', [])}")
                print(f"   Match Score:{product.get('match_percent', 0.0):.2f}%")
            else:
                print(f"   {product}") # Prints "No safe match found" if the check failed
                
    print("\n" + "="*50)
    print("🏁 MVP ROUTINE GENERATION COMPLETE")
    print("="*50)